GET http://localhost:8080/user

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "UsernameTest",
  "password": "Hello123"
}

###

PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "name": "TestUsername",
  "password": "Hello123"
}

###

DELETE http://localhost:8080/user/1


###