GET http://localhost:8081/user

###

GET http://localhost:8081/user?name=Dionis der User

###
//8081 Bei Sandro, Der Port.
GET http://localhost:8081/user/Token

###

PUT http://localhost:8081/user/1
Content-Type: application/json

{
  "name": "TestUsername",
  "password": "Hello123"
}

###

DELETE http://localhost:8081/user/delete/1

###

POST http://localhost:8081/user
Content-Type: application/json

{
  "name": "Dionis der User",
  "password": "Passwort17"
}


###

POST http://localhost:8081/user/login
Content-Type: application/json

{
  "name": "Dionis der User",
  "password": "Passwort17"
}


###

POST http://localhost:8081/user
Content-Type: application/json

{
  "name": "Test12332",
  "password": "Hello1223"
}

###

POST http://localhost:8081/Session
Content-Type: application/json

{
  "userName": "Test12332"
}

###

POST http://localhost:8081/Idea
Content-Type: application/json

{
  "description": "UsernameTest",
  "userName": "Test12332",
  "sessionId": 1
}

###
GET http://localhost:8081/Session

###

GET http://localhost:8081/Idea/sessionId/1

###

POST http://localhost:8081/Idea
Content-Type: application/json

{
  "description": "test#2",
  "userName": "Test12332",
  "sessionId": 1
}

###

POST http://localhost:8081/Session/addUser/1
Content-Type: application/json

{
  "userName": "Gabriel"
}

###

POST http://localhost:8081/Idea
Content-Type: application/json

{
  "description": "test#3",
  "userName": "Gabriel",
  "sessionId": 1
}

###
